[package]
authors = ["Patrick Auernig <dev.patrick.auernig@gmail.com>"]
name = "javelin"
description = "Simple streaming server"
keywords = ["rtmp", "hls", "live-streaming", "media"]
categories = ["multimedia", "multimedia::audio", "multimedia::video"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://gitlab.com/valeth/javelin.git"
version = "0.4.0-dev.1"
edition = "2018"


[dependencies]
bytes = "^0.5"
parking_lot = "^0.11"
futures = "^0.1"
rml_rtmp = "^0.3"
serde_yaml = "^0.8"
anyhow = "^1.0"
thiserror = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
log = { version = "^0.4", features = ["max_level_debug", "release_max_level_info"] }
fern = { version = "^0.6", features = ["colored"] }
clap = { version = "~2.33", features = ["wrap_help"] }
chrono = { version = "^0.4", features = ["serde"] }
native-tls = { version = "0.2", optional = true }
tokio-tls = { version = "0.2", optional = true }
m3u8-rs = { version = "1.0", optional = true }
tempfile = { version = "3.0", optional = true }
warp = { version = "0.1", optional = true }
serde_json = { version = "^1.0", optional = true }

[dependencies.tokio]
version = "^0.1"
default-features = false
features = ["rt-full", "io", "timer", "tcp"]

[dependencies.javelin-types]
version = "0.4.0"
path = "../javelin-types"

[dependencies.javelin-rtmp]
version = "0.4.0"
path = "../javelin-rtmp"

[dependencies.javelin-codec]
optional = true
version = "0.4.0"
path = "../javelin-codec"


[features]
default = ["tls", "hls", "web"]
tls = ["native-tls", "tokio-tls"]
hls = ["m3u8-rs", "tempfile", "javelin-codec/mpegts"]
web = ["warp", "serde_json", "hls"]
