[workspace]
members = [
    "./javelin",
    "./javelin-codec",
    "./javelin-types",
    "./javelin-core",
    "./javelin-rtmp",
]


[profile.release]
opt-level = 3
lto = false # some linking errors with lto = true
