version: "3.7"

services:
  javelin:
    image: registry.gitlab.com/valeth/javelin:develop
    build: .
    command:
      - "--permit-stream-key=123456"
    ports:
      - "1935:1935"
    volumes:
      - "./tmp/stream:/var/data"

  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./tmp/stream:/tmp/stream"
