version: "3.7"

volumes:
  hls_data:
  mongodb0:

services:
  javelin:
    image: registry.gitlab.com/valeth/javelin:develop
    build: .
    command:
      - "--permit-stream-key=123456"
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - "hls_data:/var/data"
      - "./config:/app/config"

  mongodb:
    image: "mongo:4.2"
    environment:
      MONGO_INITDB: "javelin"
      MONGO_INITDB_ROOT_USERNAME: "dev"
      MONGO_INITDB_ROOT_PASSWORD: "s3cur3"
    volumes:
      - "mongodb0:/data/db"
    ports:
      - "27017:27017"
